### ISSUE TITLE
About sampling phase

### ISSUE THREAD

**Issue by AwakerMhy** [baofff/Analytic-DPM#1]
Hi, thanks for your interesting work! I'm trying to reproduce the sampling results using the checkpoints you provide, but there is an error occurs:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/runner/cifar10/ddpm_dsm/betas_2021-08-19-23-55-32/beta_schedule_linear_num_diffusion_1000/train/ms_eps/400000_n_samples_None.ms_eps.pth'.
How should I prepare this file?

**Comment by baofff** [comment]
This file is the \Gamma vector in Eq.(8). You can prepare it by changing `phase = "save_ms_eps"` in `run_xxx.py` or using our precalculated one [[link](https://drive.google.com/file/d/1pnwxNFY-0P_IZaTVP1zNBxzKb3T1QeD7/view)]

**Comment by baofff** [comment]
> Hi, thanks for your interesting work! I'm trying to reproduce the sampling results using the checkpoints you provide, but there is an error occurs: FileNotFoundError: [Errno 2] No such file or directory: 'workspace/runner/cifar10/ddpm_dsm/betas_2021-08-19-23-55-32/beta_schedule_linear_num_diffusion_1000/train/ms_eps/400000_n_samples_None.ms_eps.pth'. How should I prepare this file?

**Comment by AwakerMhy** [comment]
Thank you, it works.
