### ISSUE TITLE
A question about DDIM

### ISSUE THREAD

**Issue by CS123n** [baofff/Analytic-DPM#2]
https://github.com/baofff/Analytic-DPM/blob/19cc628fd2ca086ddd790ab46d0abd53e6e018ee/cifar_imagenet_codes/core/inference/sampler/reverse_ddim.py#L95
Hi, very interesting work!
I have a small question about DDIM. I want to know whether your method can add no new random noise in the denoising process?

**Comment by baofff** [comment]
Our method add noise in the denoising process of DDIM. As you can see in Eq.(7) in the paper, the optimal variance is not zero for DDIM.

**Comment by CS123n** [comment]
According to my understanding, when the variance is 0, your method is completely consistent with ddim. Is this right?

**Comment by baofff** [comment]
It's right. Our method doesn't change the mean. It only modifies the variance.

**Comment by CS123n** [comment]
Get it. Thanks a lot!
