### ISSUE TITLE
Can you provide the pre-calculated statistics of the CelebA64x64 that is used for FID evaluation?

### ISSUE THREAD

**Issue by AwakerMhy** [baofff/Analytic-DPM#4]
This is really amazing work! I'm trying to calculate the FID of the output of your model on CelebA64x64. However, I notice that the FID is much higher than that reported by the paper. I think one possible reason is that we crop the CelebA in different ways, leading to different statistics. Can you provide the pre-calculated statistics of the CelebA64x64 that you used for FID evaluation?
Thank you!

**Comment by baofff** [comment]
Thanks for the suggestion. We have updated the [link](https://drive.google.com/drive/folders/1aqSXiJSFRqtqHBAsgUw4puZcRqrqOoHx?usp=sharing) to pre-calculated FID statistics on all datasets.

**Comment by AwakerMhy** [comment]
Thank you for the update!
