### ISSUE TITLE
CIFAR10 training problem

### ISSUE THREAD

**Issue by zwzhang123** [baofff/Analytic-DPM#5]
Hi, could you give any suggestion on model training? Because I have used the other two code bases  to reproduce the results, but both of them failed.

[https://github.com/luping-liu/PNDM/issues/6](https://github.com/luping-liu/PNDM/issues/6)

Thanks a lot.

**Comment by baofff** [comment]
We use [this set of hyperparameters](https://github.com/baofff/Analytic-DPM/blob/main/cifar_imagenet_codes/profiles/ddpm/cifar10/train.py) to train the CIFAR10 model.

**Comment by zwzhang123** [comment]
Thanks for your reply. I will try your code later.

**Comment by devzhk** [comment]
> 

Hi, I'm also trying to train DDPM from scratch to reproduce the paper's results. Any update?
