### ISSUE TITLE
Can you describe where in this repository does your improvement lies? I mean of course in variance estimation but in which page（your sample code is a bit mess）?And l surpose you team also added some another changes so could you please tell us where are they?

### ISSUE THREAD

**Issue by Kevin-shihello-world** [baofff/Analytic-DPM#6]
LIKE THE TITTLE thank you!

**Comment by baofff** [comment]
You can refer to [line 90-95](https://github.com/baofff/Analytic-DPM/blob/main/celeba_lsun_codes/core/inference/sampler/reverse_ddpm.py) for Analytic-DDPM and [line 84-88](https://github.com/baofff/Analytic-DPM/blob/main/celeba_lsun_codes/core/inference/sampler/reverse_ddim.py) for Analytic-DDIM.
