### ISSUE TITLE
The code does not match with Eq.(9)?

### ISSUE THREAD

**Issue by ThisisBillhe** [baofff/Analytic-DPM#7]
Hi! Thx for your excellent work!!!
There is a coeff beta_n before gamma_n in Eq.(9) I am confused why it does not appear in your code, such as line 92 in reverse_ddpm.py.
Looking forward to your reply!

**Comment by baofff** [comment]
In this code we directly store the vector of \overline{\beta}_n \Gamma_n, which is exactly the output of the noise prediction network. See line 156-168 in [this file](https://github.com/baofff/Analytic-DPM/blob/main/celeba_lsun_codes/interface/runner.py).

**Comment by ThisisBillhe** [comment]
> In this code we directly store the vector of \overline{\beta}_n \Gamma_n, which is exactly the output of the noise prediction network. See line 156-168 in [this file](https://github.com/baofff/Analytic-DPM/blob/main/celeba_lsun_codes/interface/runner.py).

Thanks!
